# Generated by Django 5.0.3 on 2024-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_articlepage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
